import { describe, it, expect } from 'vitest'
import { generateRouteTreeCode, generateTypeDefinition } from '../src/codegen'
import type { RouteNode } from '../src/types'

function makeRoute(overrides: Partial<RouteNode> & { path: string; id: string }): RouteNode {
  return {
    filePath: '',
    importPath: `src/pages${overrides.path === '/' ? '' : overrides.path}/page`,
    is404: false,
    isGlobal404: false,
    isLayout: false,
    children: [],
    parentId: undefined,
    ...overrides,
  }
}

describe('generateRouteTreeCode', () => {
  it('should generate code for a single page', () => {
    const routes = [makeRoute({ path: '/', id: 'IndexRoute' })]
    const code = generateRouteTreeCode(routes, new Map(), [], undefined, undefined, 'src/routeTree.gen.tsx', 'src/pages')
    expect(code).toContain('createRootRoute')
    expect(code).toContain('createRoute')
    expect(code).toContain("path: '/'")
    expect(code).toContain('export const routeTree')
  })

  it('should include pickExports helper', () => {
    const routes = [makeRoute({ path: '/', id: 'IndexRoute' })]
    const code = generateRouteTreeCode(routes, new Map(), [], undefined, undefined, 'src/routeTree.gen.tsx', 'src/pages')
    expect(code).toContain('function pickExports')
    expect(code).toContain("...pickExports(IndexRoutePage, 'loader', 'beforeLoad')")
  })

  it('should generate redirect routes', () => {
    const redirects = [{ from: '/old', to: '/new', permanent: true }]
    const code = generateRouteTreeCode([], new Map(), redirects, undefined, undefined, 'src/routeTree.gen.tsx', 'src/pages')
    expect(code).toContain('redirect')
    expect(code).toContain("to: '/new'")
    expect(code).toContain('statusCode: 301')
  })

  it('should generate dynamic redirect routes', () => {
    const redirects = [{ from: '/users/[id]', to: '/profile/[id]' }]
    const code = generateRouteTreeCode([], new Map(), redirects, undefined, undefined, 'src/routeTree.gen.tsx', 'src/pages')
    expect(code).toContain('params')
    expect(code).toContain('/users/$id')
  })

  it('should generate splat redirect routes', () => {
    const redirects = [{ from: '/blog/*', to: '/posts/*' }]
    const code = generateRouteTreeCode([], new Map(), redirects, undefined, undefined, 'src/routeTree.gen.tsx', 'src/pages')
    expect(code).toContain("params['*']")
  })

  it('should handle global 404', () => {
    const global404 = makeRoute({ path: '/404', id: 'NotFoundRoute', is404: true, isGlobal404: true, importPath: 'src/pages/404' })
    const code = generateRouteTreeCode([], new Map(), [], global404, undefined, 'src/routeTree.gen.tsx', 'src/pages')
    expect(code).toContain('NotFoundPage')
    expect(code).toContain('notFoundComponent')
  })

  it('should handle local 404', () => {
    const routes = [makeRoute({ path: '/users', id: 'usersRoute' })]
    const notFounds = new Map([['/users', 'src/pages/users/404']])
    const code = generateRouteTreeCode(routes, notFounds, [], undefined, undefined, 'src/routeTree.gen.tsx', 'src/pages')
    expect(code).toContain('notFoundComponent')
    expect(code).toContain('usersRouteNotFound')
  })

  it('should handle layout routes', () => {
    const layout = makeRoute({ path: '/', id: 'RootLayout', isLayout: true, importPath: 'src/pages/layout', children: [] })
    const page = makeRoute({ path: '/', id: 'IndexRoute', parentId: 'RootLayout' })
    layout.children = [page]
    const code = generateRouteTreeCode([layout], new Map(), [], undefined, undefined, 'src/routeTree.gen.tsx', 'src/pages')
    expect(code).toContain("id: '_root'")
    expect(code).toContain('RootLayout.addChildren')
  })

  it('should include auto-generated header comment', () => {
    const code = generateRouteTreeCode([], new Map(), [], undefined, undefined, 'src/routeTree.gen.tsx', 'src/pages')
    expect(code).toContain('Auto-generated by vite-plugin-tsr-next')
    expect(code).toContain('Do not edit this file manually')
  })

  it('should generate default root component when no rootComponent provided', () => {
    const code = generateRouteTreeCode([], new Map(), [], undefined, undefined, 'src/routeTree.gen.tsx', 'src/pages')
    expect(code).toContain('function RootComponent()')
    expect(code).toContain('Outlet')
  })
})

describe('generateTypeDefinition', () => {
  it('should generate valid type definition', () => {
    const code = generateTypeDefinition()
    expect(code).toContain("declare module '@tanstack/react-router'")
    expect(code).toContain('interface Register')
    expect(code).toContain('routeTree')
    expect(code).toContain('export {}')
  })
})
